[ids]
ids_node ansible_host=34.250.74.247

[victims]
victim-web ansible_host=3.255.78.42
victim-db ansible_host=3.252.246.143
victim-file ansible_host=54.74.170.117

[soc]
soc_node ansible_host=108.131.195.208

[kali]
kali-attack ansible_host=54.74.153.47 ansible_user=kali

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=terraform/nids-pfe-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
