[ids]
ids_node ansible_host=34.250.74.247

[victims]
victim-web ansible_host=54.171.175.180
victim-db ansible_host=52.51.75.224
victim-file ansible_host=52.209.3.5

[soc]
soc_node ansible_host=108.131.195.208

[kali]
kali-attack ansible_host=52.211.213.211 ansible_user=kali

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=terraform/nids-pfe-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
